### ISSUE TITLE
"This transcript is still being processed for display." error ???

### ISSUE THREAD

**Issue by simonhm** [digitalutsc/islandora_solution_pack_oralhistories#14]
Hi,
I am getting this error **"This transcript is still being processed for display."** 
I installed all of required modules/libraries. 
Even testing with the test XML transcript file on your github, I still get that error. 
What is causing it? 

* configuration details: 
![image](https://cloud.githubusercontent.com/assets/6493383/20185378/748a0144-a731-11e6-9363-666002a4a643.png)

![image](https://cloud.githubusercontent.com/assets/6493383/20185414/91458740-a731-11e6-8211-34f555317613.png)

![image](https://cloud.githubusercontent.com/assets/6493383/20185438/a9ee806c-a731-11e6-8493-ded0b213a2d3.png)

* the steps taken to upload or create the oral history object
Ingest an oral history object with mp4 and xml files (your testing XML 1st and then try different xml transcript files).
The object is ingested successfully. **I can watch the clip and see caption/subtitles**, but the transcript display is not working and showing that error. 

![image](https://cloud.githubusercontent.com/assets/6493383/20185850/3d62fb88-a733-11e6-909c-2dcf816a78d8.png)

* any other details or files that may help us reproduce the error or isolate what may be occurring for you.
I'm wondering if maybe the XML indexing into SOLR getting problem is causing this error or what ? Is this transcript display related to SOLR indexing?
Simon.

**Comment by Natkeeran** [comment]
@simonhm Thank you the detail bug report.

Would you be able to go to the solr and see if the or_transcript is being index for that object?

Also, please try un-checking "Generate datastream for WebVTT indexing" option and creating a new object? (This is relatively a new addition, and want to see if it causing any issues).

**Comment by simonhm** [comment]
I'm not good at SOLR. Other developers work with SOLR here. I will ask them about this. They're not here this morning.
So far I can't search that object on islandora site, that's why I think maybe there is something wrong with SOLR indexing, and that causes the transcript display error as well ???

Also, please try un-checking "Generate datastream for WebVTT indexing" option and creating a new object? (This is relatively a new addition, and want to see if it causing any issues).
<<< I tried it, and the transcript display is still not working.

**Comment by Natkeeran** [comment]
When using the XML for transcript, the solr does need to be configured properly for the TRANSCRIPT to display.  If the SOLR does not index it properly, then it will not display it.  Some further instructions can be found here with regards to how to configure the solr: https://github.com/digitalutsc/islandora_solution_pack_oralhistories/tree/master/docs/developer

Another option to try is to upload a WebVTT file as TRANSCRIPT, instead of the XML file.  This will provide more info into the issue.  

TRANSCRIPT.vtt
WEBVTT

00:00.000 --> 00:30.000
<v Different Speaker>This is the transcript text content.

00:30.000 --> 01:00.000
<v Speaker2>speaker 2 transcript

01:00.000 --> 01:45.000
<v Speaker 3>speaker 3 transcript FINDTHIS2

**Comment by simonhm** [comment]
We updated the SOLR indexing, and the SOLR is working now. I can search the object on Islandora site and see the or_transcript on SOLR as well.
BUT the transcript display is still not working and in process ....

![image](https://cloud.githubusercontent.com/assets/6493383/20191695/4cb0831c-a74c-11e6-823e-f1c7050e6fa9.png)

![image](https://cloud.githubusercontent.com/assets/6493383/20191725/6c658220-a74c-11e6-98a5-50c6d570e334.png)

![image](https://cloud.githubusercontent.com/assets/6493383/20191754/83658254-a74c-11e6-9766-2b79bb42e3cd.png)

Hmmh, what's going on here ?

**Comment by Natkeeran** [comment]
@simonhm, yes it does seem like oral history xml is being index.  The solr should look like below:

![http-__localhost-8080_solr_ _collection1_query](https://cloud.githubusercontent.com/assets/1827166/20193403/d3514b36-a75b-11e6-924a-0d886b74e9d5.png)

It would be easier if we can setup a skype or web meeting to review/troubleshoot this issue further.  Tomorrow morning (Toronto/Eastern time) looks good for us.

**Comment by simonhm** [comment]
If I use the VTT file to ingest object (instead of XML file), I will get this:
![image](https://cloud.githubusercontent.com/assets/6493383/20194429/ef2fe49c-a757-11e6-86e2-87fc59032dc3.png)

Click on Edit, this one shows up

![image](https://cloud.githubusercontent.com/assets/6493383/20194472/1a53f366-a758-11e6-97cf-9f80f9e84e7e.png)

I guess I know what's going on here. That is something wrong in creating/ingesting between XML and VTT files.

Skype meeting is great. Tomorrow morning is good for me also.
My Skype ID is: master.simon21@yahoo.com
Thanks.

**Comment by simonhm** [comment]
Once more thing, I couldn't see the vtt_content in SOLR. Is that something ?

**Comment by Natkeeran** [comment]
We narrowed the issue down to here: https://github.com/digitalutsc/islandora_solution_pack_oralhistories/blob/master/includes/utilities.inc#L143, with the help of this script: https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/15.  

When the sort parameter is set, @simonhm does not get a valid response.  It is unclear why, as he has similar environment and configuration as vagrant/local.  We cannot reproduce the issue here locally.  

Simon pointed out that mutli value fields may have issues with sorting.  

We noted that we may not have to set the sort parameter if the cues are ordered.  Removing that line is a work around for him, that enables him to continue.

**Comment by MarcusBarnes** [comment]
We are leaving this issue open for now pending further review.    If you encounter the same issue, please provide details by commenting below and also please see @Natkeeran's [comment](https://github.com/digitalutsc/islandora_solution_pack_oralhistories/issues/14#issuecomment-260444127) for a possible work around .

**Comment by MarcusBarnes** [comment]
Initially addressed with pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/27 (commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/1177d1340db62f38221fad3b5d317708b99b0323).
