### ISSUE TITLE
TRANSCRIPT does not get created if you add MEDIATRACK datastream in the 

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#68]
Description
Uploading an an oral history audio/video alone then adding a MEDIATRACK datastream does not create a TRANSCRIPT. However, a TRANSCRIPT gets generated if you add a MEDIATRACK datastream at the same time as adding an audio/video file.

Steps to Reproduce
1. Upload an audio/video oral history alone
2. When ingested, add a vtt MEDIATRACK datastream

Expected Behaviour
Similar to when you add a vtt (MEDIATRACK) file through the ingest steps, TRANSCRIPT gets generated from the VTT file.

Actual Behaviour
TRANSCRIPT datastream does not get created

**Comment by kimpham54** [comment]
test against https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/76 to see if this issue still persists

**Comment by Natkeeran** [comment]
@kimpham54 This issue is not related to https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/76.

The uploaded MEDIATRACK file needs to have TRANSCRIPT as the ID/Label.  Also, we only support one MEDIATRACK file currently in the transcript UI.  Being able to display the datastream with MEDIATRACK ID/Label in the transcript UI could be a desired enhancement.

**Comment by kimpham54** [comment]
oops commented on the wrong issue

**Comment by kimpham54** [comment]
I tested by adding the vtt directly to a MEDIATRACK datastream instead of a TRANSCRIPT datastream. Will test by adding the vtt to a TRANSCRIPT datastream instead. I don't think we need to worry about displaying the vtt if it's labelled MEDIATRACK.
